name: 'DrawIO'
version: '26.2.8'
slug: 'drawio'
codenotary: 'wghaos@163.com'
description: "DrawIO是运行在浏览器中的在线绘图工具"
image: jgraph/drawio
url: https://github.com/waxgourd-ha/waxgourd-addons #https://github.com/jgraph/docker-drawio
init: false
arch:
  - aarch64
  - amd64
#webui: "[PROTO:http]://[HOST]:[PORT:8080]"
#ports:
#  8080/tcp: 8080
#  8443/tcp: 8443
ingress: true
ingress_port: 8080
#host_network: true
panel_icon: 'mdi:application-variable'
boot: manual
