name: 节点小宝
version: 1.0.1
slug: jdxb
description: 'A Home Assistant add-on for jdxb service. 这是一个节点小宝客户端'
url: https://github.com/waxgourd-ha/waxgourd-addons
image: wghaos/addon-wghaos-jdxb
init: false
boot: manual
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:9118]"
ports:
  9118/tcp: 9118
#ingress: true
#ingress_port: 9118
privileged:
  - SYS_ADMIN
  - NET_ADMIN
devices:
  - /dev/net/tun
panel_icon: 'mdi:server-network'
#host_network: true
map:
  - addon_config:rw
  - config:rw
  - share:rw
  - ssl:rw