name: Fusion(仪表板)
version: 2024.10.1
slug: ha_fusion
description: Fusion一个现代化、易于使用且性能卓越的自定义Home Assistant仪表板
arch:
  - aarch64
  - amd64
  - armv7
init: false
url: https://github.com/matt8707/addon-ha-fusion
panel_icon: mdi:atom
panel_admin: false
apparmor: true
ingress: true
ingress_stream: true
hassio_api: true
ports:
  8099/tcp: null
image: matt8707/addon-ha-fusion-{arch}
boot: manual
