name: "远程 WebView 服务器"
version: "1.1.3"
slug: "remote_webview_server"
description: "把你的Home Assistant仪表盘通过WebSocket方式实时推送到ESP32的中控屏上。"
url: https://github.com/waxgourd-ha/waxgourd-addons
image: wghaos/remote-webview-server-{arch}
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
video: true
udev: true
init: false
watchdog: "[PROTO:http]://[HOST]:[PORT:18080]/"
map:
  - type: addon_config
    read_only: false
options:
  tile_size: 32
  full_frame_tile_count: 4
  full_frame_area_threshold: 0.5
  full_frame_every: 50
  every_nth_frame: 1
  min_frame_interval_ms: 80
  jpeg_quality: 85
  max_bytes_per_message: 61440
  ws_port: 8081
  debug_port: 9221
  expose_debug_proxy: true
  debug_proxy_port: 9222
  health_port: 18080
  prefers_reduced_motion: false
  user_data_dir: "/pw-data"
schema:
  tile_size: int
  full_frame_tile_count: int
  full_frame_area_threshold: float
  full_frame_every: int
  every_nth_frame: int
  min_frame_interval_ms: int
  jpeg_quality: int
  max_bytes_per_message: int
  ws_port: int
  debug_port: int
  expose_debug_proxy: bool
  debug_proxy_port: int
  health_port: int
  prefers_reduced_motion: bool
  user_data_dir: str