name: 奥特曼机器人
slug: autman
description: '机器人自动化工具'
url: https://github.com/waxgourd-ha/waxgourd-addons
version: 1.0.0
image: wghaos/autman
init: false
docker_api: true
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:8162]"
ports:
  8080/tcp: 8162
boot: manual
