name: docker日志监控Dozzle
version: 8.10.4
slug: dozzle
codenotary: wghaos@163.com
description: 'Dozzle 是一个小型轻量级应用程序，具有基于 Web 的界面来监控 Docker 日志'
url: https://github.com/waxgourd-ha/waxgourd-addons
image: wghaos/dozzle
init: false
arch:
  - aarch64
  - amd64
docker_api: true
webui: "[PROTO:http]://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
boot: manual
