name: Beszel Hub
version: 0.17.0
slug: beszel-hub
description: Beszel Hub 是一个轻量级服务器监控平台，包含 Docker 统计信息、历史数据和告警功能
url: https://github.com/waxgourd-ha/waxgourd-addons
#image: henrygd/beszel
image: wghaos/addon-wghaos-beszel
init: false
arch:
  - aarch64
  - amd64
startup: application
apparmor: false
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: "WEB服务端口"
webui: http://[HOST]:[PORT:8090]
boot: manual
hassio_api: false