name: "EasyTier"
version: "2.5.0"
slug: "easytier"
description: "基于EasyTier的快速组网工具"
url: "https://github.com/waxgourd-ha/waxgourd-addons"
image: "wghaos/easytier"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
options:
  username: ""
  env_vars: []
schema:
  username: str?
  env_vars:
    - name: str?
      value: str?