name: 'Excalidraw'
version: '0.18.0'
slug: 'excalidraw'
description: "Excalidraw是支持多人协同的私有化在线画板工具"
image: wghaos/excalidraw
url: https://github.com/waxgourd-ha/waxgourd-addons
init: false
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3000
panel_icon: 'mdi:application-variable'
boot: manual
