name: "ZigStarGW MT WEB"
version: 0.2.1
slug: zigstargw-mt-web
description: ZigStarGW MT WEB
url: https://github.com/waxgourd-ha/waxgourd-addons
arch:
  - aarch64
  - amd64
image: wghaos/zigstargw-mt-web-{arch}
init: false
boot: manual
ingress: true
ingress_port: 5550
usb: true
uart: true
privileged:
  - SYS_MODULE
  - SYS_RAWIO
host_network: true
