name: "zigbee2MQTT分身"
version: "1.3.0"
slug: "addon-zigbee2mqtt-twin"
description: "zigbee2MQTT分身"
image: wghaos/addon-wghaos-zigbee2mqtt-copy
url: https://github.com/waxgourd-ha/waxgourd-addons
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 9876
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
map:
  - addons:rw
apparmor: true
docker_api: true
startup: services
boot: manual
full_access: true

